apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: theia-{{ .Values.user }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}

spec:
  rules:
    - host: {{ .Values.user }}.{{ .Values.workspaceDomain }}
      http:
        paths:
          - backend:
              serviceName: theia-{{ .Values.user }}
              servicePort: 80
            path: /
  {{- if .Values.ingressKey }}
  tls:
    - secretName: theia-{{ .Values.user }}-cert
  {{- end }}
