apiVersion: v1
kind: Secret
metadata:
  name: theia-{{ .Values.user }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
type: Opaque
data:
  password: {{ b64enc .Values.password }}
  user: {{ b64enc .Values.user }}

