apiVersion: v1
kind: Secret
metadata:
  name: theia-{{ .Values.user }}-cert
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingressCrt | b64enc }}
  tls.key: {{ .Values.ingressKey | b64enc }}
